name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        molstar: ['5.6.0', '5.7.0']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm i --no-save molstar@${{ matrix.molstar }}
      - run: npm run typecheck
      - run: npm test
